/**
 * Static UI chrome strings (buttons, headings, settings labels).
 * Dynamic text (stage names, goals, coach lines…) arrives pre-localized in
 * the view-models; only the frame around it lives here.
 *
 * Placeholders use `{name}` and are filled with `fmt()`.
 */
import type { Lang } from '../contracts';

const es = {
  appName: 'JONRÓN',
  tagline: 'Solo tú, el bate y la cerca.',
  loading: 'Cargando…',

  // Common
  back: 'Atrás',
  cancel: 'Cancelar',
  close: 'Cerrar',
  locked: 'Bloqueado',
  stars: 'Estrellas',
  starsOf: '{n} de {m} estrellas',

  // Title
  continue: 'Continuar',
  play: 'Jugar',
  campaign: 'Campaña',
  campaignDesc: '25 etapas · 5 estadios',
  practice: 'Práctica',
  practiceDesc: 'Afina tu swing sin presión',
  derby: 'Derby',
  derbyDesc: 'Jonrones sin fin',
  settings: 'Ajustes',
  derbyBest: 'Récord Derby',
  mainMenu: 'Menú principal',

  // Campaign
  chapter: 'Capítulo',
  boss: 'Jefe',
  todDay: 'Día',
  todSunset: 'Atardecer',
  todNight: 'Noche',
  stageLocked: 'Etapa bloqueada',
  stageCompleted: 'Completada',
  stageNext: 'Siguiente',
  chapterLocked: 'Completa el capítulo anterior',
  batLocker: 'Casillero de bates',
  batInUse: 'En uso',
  batEquip: 'Equipar',
  batNeeds: 'Necesitas {n} estrellas',

  // Stage intro
  stage: 'Etapa',
  bossStage: 'Jefe final',
  pitcher: 'Lanzador',
  arsenal: 'Repertorio',
  goal: 'Objetivo',
  limit: 'Límite',
  coachTip: 'Consejo del coach',
  controls: 'Controles',
  letsBat: '¡A batear!',
  starMet: 'Conseguida',

  // Practice
  practiceTitle: 'Práctica libre',
  stadium: 'Estadio',
  pitches: 'Lanzamientos',
  all: 'Todos',
  speed: 'Velocidad',
  speedSlow: 'Lenta',
  speedNormal: 'Normal',
  speedFast: 'Rápida',
  location: 'Ubicación',
  locMiddle: 'Al centro',
  locZone: 'En la zona',
  locAny: 'Cualquiera',
  pitcherHand: 'Lanzador',
  handR: 'Derecho',
  handL: 'Zurdo',
  pickOnePitch: 'Elige al menos un lanzamiento',
  letsPractice: '¡A practicar!',

  // Derby
  derbyTitle: 'Derby de jonrones',
  rules: 'Reglas',
  best: 'Récord',
  noBest: 'Sin récord',
  chooseStadium: 'Elige tu estadio',
  letsDerby: '¡A jugar!',

  // Settings
  settingsTitle: 'Ajustes',
  secGame: 'Juego',
  secVideo: 'Gráficos',
  secAudio: 'Sonido',
  secAssist: 'Ayudas',
  secTiming: 'Sincronía',
  secData: 'Datos',
  language: 'Idioma',
  controlMode: 'Modo de control',
  modePro: 'Pro',
  modeCasual: 'Casual',
  modeProDesc: 'Apuntas el círculo de contacto y mides el tiempo. Control total.',
  modeCasualDesc: 'Solo mides el tiempo: el círculo apunta solo. Ideal para empezar.',
  handedness: 'Bateas',
  righty: 'Diestro',
  lefty: 'Zurdo',
  quality: 'Calidad',
  qAuto: 'Auto',
  qLow: 'Baja',
  qMedium: 'Media',
  qHigh: 'Alta',
  units: 'Unidades',
  imperial: 'ft · mph',
  metric: 'm · km/h',
  volMaster: 'General',
  volSfx: 'Efectos',
  volMusic: 'Música',
  volCrowd: 'Público',
  latency: 'Ajuste de latencia',
  latencyDesc: 'Compensa el retraso de tu pantalla y audio.',
  calibrate: 'Calibrar',
  reducedMotion: 'Reducir animaciones',
  pitchTrail: 'Estela de la bola',
  showTimingMs: 'Timing en milisegundos',
  showPitchType: 'Mostrar tipo de lanzamiento',
  resetProgress: 'Borrar progreso',
  resetDesc: 'Elimina estrellas, récords y bates.',
  resetConfirm: '¿Seguro? No se puede deshacer.',
  resetYes: 'Sí, borrar',

  // Calibration
  calTitle: 'Calibrar latencia',
  calIntro: 'Vas a oír 8 clics. Toca la pantalla o pulsa Espacio justo en cada clic.',
  calIntro2: 'Los 2 primeros son de calentamiento y no cuentan.',
  calStart: 'Empezar',
  calTap: 'Toca al ritmo',
  calTapKey: 'Toca o pulsa Espacio',
  calWarmup: 'Calentamiento',
  calCounting: 'Midiendo',
  calResult: 'Tu desfase',
  calLate: 'Tocas {ms} ms tarde. Lo compensamos por ti.',
  calEarly: 'Tocas {ms} ms antes. Lo compensamos por ti.',
  calSpot: '¡En el clavo! Tu sincronía es perfecta.',
  calNotEnough: 'No captamos suficientes toques. Inténtalo otra vez.',
  calApply: 'Aplicar',
  calRetry: 'Repetir',
  calEarlyAxis: 'Antes',
  calLateAxis: 'Tarde',

  // HUD
  outs: 'Outs',
  outsAria: 'Quedan {left} de {total} outs',
  time: 'Tiempo',
  timeAria: 'Quedan {s} segundos',
  streak: 'Racha',
  streakAria: 'Racha de {n}',
  score: 'Marcador',
  pause: 'Pausa',
  swing: 'Batear',
  power: 'Potencia',
  powerAria: 'Swing de potencia',
  coach: 'Coach',
  dismissTip: 'Cerrar consejo',
  timing: 'Timing',

  // Pause
  pauseTitle: 'Pausa',
  resume: 'Continuar',
  restart: 'Reiniciar',
  quit: 'Salir al menú',

  // Results
  retry: 'Reintentar',
  next: 'Siguiente',
  menu: 'Menú',
  share: 'Compartir',
  unlocked: 'Desbloqueado',
  newStar: '¡Nueva!',
  summary: 'Resumen',
} as const;

export type StringKey = keyof typeof es;
export type Strings = { readonly [K in StringKey]: string };

const en: Strings = {
  appName: 'JONRÓN',
  tagline: 'Just you, the bat and the fence.',
  loading: 'Loading…',

  back: 'Back',
  cancel: 'Cancel',
  close: 'Close',
  locked: 'Locked',
  stars: 'Stars',
  starsOf: '{n} of {m} stars',

  continue: 'Continue',
  play: 'Play',
  campaign: 'Campaign',
  campaignDesc: '25 stages · 5 ballparks',
  practice: 'Practice',
  practiceDesc: 'Tune your swing, no pressure',
  derby: 'Derby',
  derbyDesc: 'Endless home runs',
  settings: 'Settings',
  derbyBest: 'Derby best',
  mainMenu: 'Main menu',

  chapter: 'Chapter',
  boss: 'Boss',
  todDay: 'Day',
  todSunset: 'Sunset',
  todNight: 'Night',
  stageLocked: 'Stage locked',
  stageCompleted: 'Completed',
  stageNext: 'Next up',
  chapterLocked: 'Clear the previous chapter',
  batLocker: 'Bat locker',
  batInUse: 'Equipped',
  batEquip: 'Equip',
  batNeeds: 'Requires {n} stars',

  stage: 'Stage',
  bossStage: 'Boss fight',
  pitcher: 'Pitcher',
  arsenal: 'Arsenal',
  goal: 'Goal',
  limit: 'Limit',
  coachTip: 'Coach’s tip',
  controls: 'Controls',
  letsBat: 'Play ball!',
  starMet: 'Earned',

  practiceTitle: 'Free practice',
  stadium: 'Ballpark',
  pitches: 'Pitches',
  all: 'All',
  speed: 'Speed',
  speedSlow: 'Slow',
  speedNormal: 'Normal',
  speedFast: 'Fast',
  location: 'Location',
  locMiddle: 'Middle',
  locZone: 'In the zone',
  locAny: 'Anywhere',
  pitcherHand: 'Pitcher',
  handR: 'Righty',
  handL: 'Lefty',
  pickOnePitch: 'Pick at least one pitch',
  letsPractice: 'Start practice',

  derbyTitle: 'Home Run Derby',
  rules: 'Rules',
  best: 'Best',
  noBest: 'No record yet',
  chooseStadium: 'Pick your ballpark',
  letsDerby: 'Let’s go!',

  settingsTitle: 'Settings',
  secGame: 'Game',
  secVideo: 'Graphics',
  secAudio: 'Audio',
  secAssist: 'Assists',
  secTiming: 'Timing',
  secData: 'Data',
  language: 'Language',
  controlMode: 'Control mode',
  modePro: 'Pro',
  modeCasual: 'Casual',
  modeProDesc: 'Aim the contact circle and time your swing. Full control.',
  modeCasualDesc: 'Timing only: the circle aims itself. Great for starters.',
  handedness: 'Bats',
  righty: 'Right',
  lefty: 'Left',
  quality: 'Quality',
  qAuto: 'Auto',
  qLow: 'Low',
  qMedium: 'Medium',
  qHigh: 'High',
  units: 'Units',
  imperial: 'ft · mph',
  metric: 'm · km/h',
  volMaster: 'Master',
  volSfx: 'Effects',
  volMusic: 'Music',
  volCrowd: 'Crowd',
  latency: 'Latency offset',
  latencyDesc: 'Compensates for display and audio delay.',
  calibrate: 'Calibrate',
  reducedMotion: 'Reduce motion',
  pitchTrail: 'Pitch trail',
  showTimingMs: 'Timing in milliseconds',
  showPitchType: 'Show pitch type',
  resetProgress: 'Reset progress',
  resetDesc: 'Erases stars, records and bats.',
  resetConfirm: 'Are you sure? This can’t be undone.',
  resetYes: 'Yes, reset',

  calTitle: 'Calibrate latency',
  calIntro: 'You’ll hear 8 clicks. Tap the screen or press Space right on each click.',
  calIntro2: 'The first 2 are warm-up and don’t count.',
  calStart: 'Start',
  calTap: 'Tap to the beat',
  calTapKey: 'Tap or press Space',
  calWarmup: 'Warm-up',
  calCounting: 'Measuring',
  calResult: 'Your offset',
  calLate: 'You tap {ms} ms late. We’ll compensate.',
  calEarly: 'You tap {ms} ms early. We’ll compensate.',
  calSpot: 'Spot on! Your timing is perfect.',
  calNotEnough: 'We didn’t catch enough taps. Try again.',
  calApply: 'Apply',
  calRetry: 'Retry',
  calEarlyAxis: 'Early',
  calLateAxis: 'Late',

  outs: 'Outs',
  outsAria: '{left} of {total} outs left',
  time: 'Time',
  timeAria: '{s} seconds left',
  streak: 'Streak',
  streakAria: 'Streak of {n}',
  score: 'Score',
  pause: 'Pause',
  swing: 'Swing',
  power: 'Power',
  powerAria: 'Power swing',
  coach: 'Coach',
  dismissTip: 'Dismiss tip',
  timing: 'Timing',

  pauseTitle: 'Paused',
  resume: 'Resume',
  restart: 'Restart',
  quit: 'Quit to menu',

  retry: 'Retry',
  next: 'Next',
  menu: 'Menu',
  share: 'Share',
  unlocked: 'Unlocked',
  newStar: 'New!',
  summary: 'Summary',
};

export const STRINGS: Record<Lang, Strings> = { es, en };

/** Fills `{key}` placeholders. */
export function fmt(template: string, values: Record<string, string | number>): string {
  return template.replace(/\{(\w+)\}/g, (m, k: string) => (k in values ? String(values[k]) : m));
}
