import type { StadiumDef, StadiumId } from '../contracts';

/**
 * Five fictional ballparks, one per campaign chapter. Each one changes the
 * physics (air density), the fence profile and the mood, so progression is
 * felt rather than just read.
 */
export const STADIUMS: Record<StadiumId, StadiumDef> = {
  solar: {
    id: 'solar',
    name: { es: 'El Solar', en: 'The Sandlot' },
    subtitle: { es: 'Donde empieza todo', en: 'Where it all begins' },
    timeOfDay: 'day',
    altitudeM: 40,
    airDensity: 1.2,
    fence: { distancesFt: [285, 300, 315, 300, 285], heightsFt: [7, 7, 7, 7, 7] },
    palette: {
      grass: '#5f9e3a',
      grassAlt: '#548f33',
      dirt: '#b9875a',
      wall: '#8a8f94',
      wallTrim: '#f2c84b',
      seats: ['#8c6a4a', '#7a5c40'],
      crowd: ['#e63946', '#f1faee', '#457b9d', '#ffb703', '#2a9d8f', '#fb8500'],
      accent: '#ffb703',
    },
    features: { lightTowers: false, fireworks: false, sea: false, mountains: false, skyline: false, sandlot: true },
    crowdDensity: 0.25,
  },
  malecon: {
    id: 'malecon',
    name: { es: 'Parque del Malecón', en: 'Seawall Park' },
    subtitle: { es: 'Atardecer frente al mar', en: 'Sunset by the sea' },
    timeOfDay: 'sunset',
    altitudeM: 5,
    airDensity: 1.17,
    fence: { distancesFt: [310, 355, 395, 365, 330], heightsFt: [34, 14, 10, 10, 8] },
    palette: {
      grass: '#4f9a45',
      grassAlt: '#45893c',
      dirt: '#c08a5b',
      wall: '#1d5c63',
      wallTrim: '#ffd166',
      seats: ['#0f4c5c', '#e36414'],
      crowd: ['#ffffff', '#e36414', '#0f4c5c', '#fb8b24', '#9a031e', '#5f0f40'],
      accent: '#fb8b24',
    },
    features: { lightTowers: true, fireworks: false, sea: true, mountains: false, skyline: false, sandlot: false },
    crowdDensity: 0.6,
  },
  metro: {
    id: 'metro',
    name: { es: 'Estadio Metropolitano', en: 'Metro Stadium' },
    subtitle: { es: 'Noche de luces en la ciudad', en: 'Bright lights, big city' },
    timeOfDay: 'night',
    altitudeM: 60,
    airDensity: 1.21,
    fence: { distancesFt: [330, 375, 400, 375, 330], heightsFt: [10, 10, 10, 10, 10] },
    palette: {
      grass: '#3f8f3f',
      grassAlt: '#367d36',
      dirt: '#a8744b',
      wall: '#14213d',
      wallTrim: '#fca311',
      seats: ['#1d3557', '#e63946'],
      crowd: ['#e63946', '#f1faee', '#a8dadc', '#457b9d', '#1d3557', '#ffd60a'],
      accent: '#fca311',
    },
    features: { lightTowers: true, fireworks: false, sea: false, mountains: false, skyline: true, sandlot: false },
    crowdDensity: 0.8,
  },
  cumbre: {
    id: 'cumbre',
    name: { es: 'Estadio La Cumbre', en: 'Summit Field' },
    subtitle: { es: '1.600 m: el aire es fino, la bola vuela', en: '5,200 ft: thin air, long balls' },
    timeOfDay: 'day',
    altitudeM: 1600,
    airDensity: 0.98,
    fence: { distancesFt: [347, 390, 415, 390, 350], heightsFt: [8, 8, 8, 8, 8] },
    palette: {
      grass: '#4a9b4f',
      grassAlt: '#408a45',
      dirt: '#9c6b43',
      wall: '#2b2d42',
      wallTrim: '#8ecae6',
      seats: ['#5c677d', '#023e8a'],
      crowd: ['#023e8a', '#ffffff', '#8ecae6', '#ef233c', '#ffb703', '#2b2d42'],
      accent: '#8ecae6',
    },
    features: { lightTowers: false, fireworks: false, sea: false, mountains: true, skyline: false, sandlot: false },
    crowdDensity: 0.7,
  },
  final: {
    id: 'final',
    name: { es: 'Coliseo de la Gran Final', en: 'Grand Final Coliseum' },
    subtitle: { es: 'Una noche, un campeón', en: 'One night, one champion' },
    timeOfDay: 'night',
    altitudeM: 20,
    airDensity: 1.2,
    fence: { distancesFt: [335, 380, 405, 380, 330], heightsFt: [10, 10, 12, 10, 10] },
    palette: {
      grass: '#3c8d40',
      grassAlt: '#327a36',
      dirt: '#a46f45',
      wall: '#240046',
      wallTrim: '#ffd60a',
      seats: ['#3c096c', '#ffd60a'],
      crowd: ['#ffd60a', '#ffffff', '#9d4edd', '#ff006e', '#3a86ff', '#240046'],
      accent: '#ffd60a',
    },
    features: { lightTowers: true, fireworks: true, sea: false, mountains: false, skyline: true, sandlot: false },
    crowdDensity: 1,
  },
};

export const STADIUM_ORDER: StadiumId[] = ['solar', 'malecon', 'metro', 'cumbre', 'final'];
